export const COMMENT_STYLES = {
  cFamily: {
    lineComment: ['//'],
    blockComment: [['/*', '*/']],
  },
  hash: {
    lineComment: ['#'],
    blockComment: [],
  },
  dashDash: {
    lineComment: ['--'],
    blockComment: [],
  },
  html: {
    lineComment: [],
    blockComment: [['<!--', '-->']],
  },
  python: {
    lineComment: ['#'],
    blockComment: [],
    docstring: ['"""', "'''"],
  },
  percent: {
    lineComment: ['%'],
    blockComment: [],
  },
  powershell: {
    lineComment: ['#'],
    blockComment: [['<#', '#>']],
  },
  semicolon: {
    lineComment: [';'],
    blockComment: [],
  },
};

export const EXT_TO_STYLE = {
  '.js': 'cFamily',
  '.jsx': 'cFamily',
  '.mjs': 'cFamily',
  '.cjs': 'cFamily',
  '.ts': 'cFamily',
  '.tsx': 'cFamily',
  '.mts': 'cFamily',
  '.cts': 'cFamily',
  '.java': 'cFamily',
  '.kt': 'cFamily',
  '.kts': 'cFamily',
  '.scala': 'cFamily',
  '.groovy': 'cFamily',
  '.gradle': 'cFamily',
  '.c': 'cFamily',
  '.h': 'cFamily',
  '.cpp': 'cFamily',
  '.cc': 'cFamily',
  '.cxx': 'cFamily',
  '.hpp': 'cFamily',
  '.hh': 'cFamily',
  '.hxx': 'cFamily',
  '.cs': 'cFamily',
  '.go': 'cFamily',
  '.rs': 'cFamily',
  '.swift': 'cFamily',
  '.php': 'cFamily',
  '.dart': 'cFamily',
  '.d': 'cFamily',
  '.m': 'cFamily',
  '.mm': 'cFamily',
  '.css': 'cFamily',
  '.scss': 'cFamily',
  '.sass': 'cFamily',
  '.less': 'cFamily',
  '.styl': 'cFamily',
  '.proto': 'cFamily',
  '.jsonc': 'cFamily',
  '.json5': 'cFamily',
  '.fs': 'cFamily',
  '.fsx': 'cFamily',
  '.zig': 'cFamily',

  '.py': 'python',

  '.rb': 'hash',
  '.sh': 'hash',
  '.bash': 'hash',
  '.zsh': 'hash',
  '.ksh': 'hash',
  '.fish': 'hash',
  '.yaml': 'hash',
  '.yml': 'hash',
  '.toml': 'hash',
  '.ini': 'hash',
  '.cfg': 'hash',
  '.conf': 'hash',
  '.pl': 'hash',
  '.pm': 'hash',
  '.r': 'hash',
  '.jl': 'hash',
  '.mk': 'hash',
  '.tf': 'hash',
  '.nix': 'hash',
  '.gitignore': 'hash',
  '.dockerignore': 'hash',
  '.env': 'hash',
  '.bashrc': 'hash',
  '.zshrc': 'hash',
  '.profile': 'hash',

  '.sql': 'dashDash',
  '.lua': 'dashDash',
  '.hs': 'dashDash',
  '.elm': 'dashDash',
  '.ada': 'dashDash',
  '.adb': 'dashDash',
  '.ads': 'dashDash',

  '.html': 'html',
  '.htm': 'html',
  '.xml': 'html',
  '.md': 'html',
  '.markdown': 'html',
  '.svg': 'html',
  '.vue': 'html',
  '.svelte': 'html',
  '.xaml': 'html',
  '.jsp': 'html',
  '.xhtml': 'html',

  '.tex': 'percent',
  '.erl': 'percent',

  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.psd1': 'powershell',

  '.lisp': 'semicolon',
  '.cl': 'semicolon',
  '.el': 'semicolon',
  '.clj': 'semicolon',
  '.cljs': 'semicolon',
  '.cljc': 'semicolon',
  '.scm': 'semicolon',
  '.rkt': 'semicolon',
  '.asm': 'semicolon',
  '.s': 'semicolon',
};

export const SPECIAL_FILE_NAMES = {
  dockerfile: 'hash',
  makefile: 'hash',
  rakefile: 'hash',
  gemfile: 'hash',
  procfile: 'hash',
  'cmakelists.txt': 'hash',
  'meson.build': 'hash',
};
