export const NODE_FRAMEWORKS = {
  'react': 'React',
  'react-dom': 'React',
  'react-native': 'React Native',
  'expo': 'Expo',
  'vue': 'Vue.js',
  '@vue/runtime-core': 'Vue.js',
  '@angular/core': 'Angular',
  'svelte': 'Svelte',
  'preact': 'Preact',
  'solid-js': 'Solid',
  'lit': 'Lit',
  'next': 'Next.js',
  'nuxt': 'Nuxt',
  '@nuxt/kit': 'Nuxt',
  '@remix-run/react': 'Remix',
  '@sveltejs/kit': 'SvelteKit',
  'astro': 'Astro',
  'gatsby': 'Gatsby',
  'express': 'Express',
  '@nestjs/core': 'NestJS',
  'fastify': 'Fastify',
  'koa': 'Koa',
  '@hapi/hapi': 'Hapi',
  'hono': 'Hono',
  'electron': 'Electron',
  'tauri': 'Tauri',
  'mongoose': 'Mongoose',
  'sequelize': 'Sequelize',
  'typeorm': 'TypeORM',
  'prisma': 'Prisma',
  '@prisma/client': 'Prisma',
  'knex': 'Knex',
  'drizzle-orm': 'Drizzle ORM',
  'apollo-server': 'Apollo Server',
  '@apollo/server': 'Apollo Server',
  '@apollo/client': 'Apollo Client',
  'graphql': 'GraphQL',
  'typescript': 'TypeScript',
  'jest': 'Jest',
  'vitest': 'Vitest',
  'mocha': 'Mocha',
  'jasmine': 'Jasmine',
  'cypress': 'Cypress',
  'playwright': 'Playwright',
  '@playwright/test': 'Playwright',
  'tailwindcss': 'Tailwind CSS',
  'bootstrap': 'Bootstrap',
};

export const NODE_BUILD_TOOLS = {
  'webpack': 'Webpack',
  'vite': 'Vite',
  'rollup': 'Rollup',
  'parcel': 'Parcel',
  'esbuild': 'esbuild',
  'gulp': 'Gulp',
  'grunt': 'Grunt',
  'turbo': 'Turborepo',
  'nx': 'Nx',
  'lerna': 'Lerna',
  'rush': 'Rush',
  'tsup': 'tsup',
  'swc': 'SWC',
  '@swc/core': 'SWC',
};

export const NODE_DB_HINTS = {
  'pg': 'PostgreSQL',
  'pg-promise': 'PostgreSQL',
  'postgres': 'PostgreSQL',
  'mysql': 'MySQL',
  'mysql2': 'MySQL',
  'sqlite3': 'SQLite',
  'better-sqlite3': 'SQLite',
  'mongodb': 'MongoDB',
  'mongoose': 'MongoDB',
  'redis': 'Redis',
  'ioredis': 'Redis',
  'cassandra-driver': 'Cassandra',
  '@elastic/elasticsearch': 'Elasticsearch',
  'neo4j-driver': 'Neo4j',
};

export const PYTHON_FRAMEWORKS = {
  'django': 'Django',
  'flask': 'Flask',
  'fastapi': 'FastAPI',
  'starlette': 'Starlette',
  'tornado': 'Tornado',
  'pyramid': 'Pyramid',
  'bottle': 'Bottle',
  'sanic': 'Sanic',
  'aiohttp': 'aiohttp',
  'numpy': 'NumPy',
  'pandas': 'pandas',
  'scipy': 'SciPy',
  'scikit-learn': 'scikit-learn',
  'tensorflow': 'TensorFlow',
  'torch': 'PyTorch',
  'pytorch': 'PyTorch',
  'keras': 'Keras',
  'pytest': 'pytest',
  'sqlalchemy': 'SQLAlchemy',
  'djangorestframework': 'Django REST Framework',
  'django-rest-framework': 'Django REST Framework',
  'celery': 'Celery',
  'requests': 'Requests',
  'httpx': 'HTTPX',
  'pydantic': 'Pydantic',
};

export const PHP_FRAMEWORKS = {
  'laravel/framework': 'Laravel',
  'symfony/symfony': 'Symfony',
  'symfony/framework-bundle': 'Symfony',
  'codeigniter4/framework': 'CodeIgniter',
  'codeigniter/framework': 'CodeIgniter',
  'cakephp/cakephp': 'CakePHP',
  'yiisoft/yii2': 'Yii',
  'slim/slim': 'Slim',
  'phpunit/phpunit': 'PHPUnit',
  'doctrine/orm': 'Doctrine ORM',
};

export const RUBY_FRAMEWORKS = {
  'rails': 'Rails',
  'sinatra': 'Sinatra',
  'rack': 'Rack',
  'rspec': 'RSpec',
  'rspec-rails': 'RSpec',
  'sidekiq': 'Sidekiq',
  'puma': 'Puma',
};

export const JAVA_FRAMEWORK_KEYWORDS = {
  'org.springframework.boot': 'Spring Boot',
  'org.springframework': 'Spring',
  'io.quarkus': 'Quarkus',
  'io.micronaut': 'Micronaut',
  'org.hibernate': 'Hibernate',
  'org.junit': 'JUnit',
  'io.vertx': 'Vert.x',
  'play.': 'Play Framework',
};

export const GO_MODULE_HINTS = {
  'github.com/gin-gonic/gin': 'Gin',
  'github.com/labstack/echo': 'Echo',
  'github.com/gofiber/fiber': 'Fiber',
  'github.com/beego/beego': 'Beego',
  'github.com/gorilla/mux': 'Gorilla Mux',
  'github.com/go-chi/chi': 'Chi',
  'gorm.io/gorm': 'GORM',
  'github.com/spf13/cobra': 'Cobra',
};

export const RUST_CRATE_HINTS = {
  'actix-web': 'Actix Web',
  'rocket': 'Rocket',
  'axum': 'Axum',
  'warp': 'Warp',
  'tokio': 'Tokio',
  'serde': 'Serde',
  'diesel': 'Diesel',
  'sqlx': 'SQLx',
  'clap': 'Clap',
};

export const BUILD_CONFIG_FILES = {
  'webpack.config.js': 'Webpack',
  'webpack.config.ts': 'Webpack',
  'webpack.config.mjs': 'Webpack',
  'vite.config.js': 'Vite',
  'vite.config.ts': 'Vite',
  'vite.config.mjs': 'Vite',
  'rollup.config.js': 'Rollup',
  'rollup.config.mjs': 'Rollup',
  'rollup.config.ts': 'Rollup',
  'gulpfile.js': 'Gulp',
  'gruntfile.js': 'Grunt',
  'esbuild.config.js': 'esbuild',
  'turbo.json': 'Turborepo',
  'nx.json': 'Nx',
  'lerna.json': 'Lerna',
  'rush.json': 'Rush',
  '.babelrc': 'Babel',
  'babel.config.js': 'Babel',
  'babel.config.json': 'Babel',
};
