export const EXT_TO_LANGUAGE = {
  '.js': 'JavaScript',
  '.jsx': 'JavaScript (JSX)',
  '.mjs': 'JavaScript',
  '.cjs': 'JavaScript',
  '.ts': 'TypeScript',
  '.tsx': 'TypeScript (TSX)',
  '.mts': 'TypeScript',
  '.cts': 'TypeScript',
  '.py': 'Python',
  '.pyi': 'Python',
  '.java': 'Java',
  '.kt': 'Kotlin',
  '.kts': 'Kotlin',
  '.scala': 'Scala',
  '.groovy': 'Groovy',
  '.c': 'C',
  '.h': 'C/C++ Header',
  '.cpp': 'C++',
  '.cc': 'C++',
  '.cxx': 'C++',
  '.hpp': 'C++ Header',
  '.hh': 'C++ Header',
  '.hxx': 'C++ Header',
  '.cs': 'C#',
  '.go': 'Go',
  '.rs': 'Rust',
  '.swift': 'Swift',
  '.php': 'PHP',
  '.rb': 'Ruby',
  '.dart': 'Dart',
  '.lua': 'Lua',
  '.pl': 'Perl',
  '.pm': 'Perl',
  '.r': 'R',
  '.jl': 'Julia',
  '.m': 'Objective-C',
  '.mm': 'Objective-C++',
  '.sh': 'Shell',
  '.bash': 'Shell',
  '.zsh': 'Shell',
  '.ksh': 'Shell',
  '.fish': 'Shell',
  '.ps1': 'PowerShell',
  '.psm1': 'PowerShell',
  '.psd1': 'PowerShell',
  '.sql': 'SQL',
  '.html': 'HTML',
  '.htm': 'HTML',
  '.xhtml': 'HTML',
  '.xml': 'XML',
  '.svg': 'SVG',
  '.css': 'CSS',
  '.scss': 'SCSS',
  '.sass': 'Sass',
  '.less': 'Less',
  '.styl': 'Stylus',
  '.vue': 'Vue',
  '.svelte': 'Svelte',
  '.md': 'Markdown',
  '.markdown': 'Markdown',
  '.mdx': 'MDX',
  '.yaml': 'YAML',
  '.yml': 'YAML',
  '.toml': 'TOML',
  '.json': 'JSON',
  '.jsonc': 'JSON with Comments',
  '.json5': 'JSON5',
  '.proto': 'Protocol Buffers',
  '.hs': 'Haskell',
  '.lhs': 'Haskell',
  '.elm': 'Elm',
  '.ex': 'Elixir',
  '.exs': 'Elixir',
  '.erl': 'Erlang',
  '.hrl': 'Erlang',
  '.clj': 'Clojure',
  '.cljs': 'ClojureScript',
  '.cljc': 'Clojure',
  '.fs': 'F#',
  '.fsx': 'F#',
  '.fsi': 'F#',
  '.nim': 'Nim',
  '.zig': 'Zig',
  '.v': 'V',
  '.cr': 'Crystal',
  '.d': 'D',
  '.ada': 'Ada',
  '.adb': 'Ada',
  '.ads': 'Ada',
  '.tex': 'TeX',
  '.mk': 'Makefile',
  '.gradle': 'Gradle',
  '.tf': 'Terraform',
  '.nix': 'Nix',
  '.lisp': 'Common Lisp',
  '.cl': 'Common Lisp',
  '.el': 'Emacs Lisp',
  '.scm': 'Scheme',
  '.rkt': 'Racket',
  '.asm': 'Assembly',
  '.s': 'Assembly',
};

export const SPECIAL_FILE_TO_LANGUAGE = {
  dockerfile: 'Dockerfile',
  makefile: 'Makefile',
  rakefile: 'Ruby',
  gemfile: 'Ruby',
  procfile: 'Procfile',
  'cmakelists.txt': 'CMake',
  'meson.build': 'Meson',
};
